name: CMake

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
    BUILD_TYPE: Release  # Release, Debug, RelWithDebInfo, etc.
    BUILD_TESTS: ON

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: "Install dependencies"
              run: sudo apt-get install -y libeigen3-dev libfmt-dev libgtest-dev libspdlog-dev

            - name: "Configure CMake"
              run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=${{env.BUILD_TESTS}}

            - name: "Build with CMake"
              run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

            - name: "Check unit tests"
              working-directory: ${{github.workspace}}/build
              run: make test
